-- Create tcg_sets table with era
CREATE TABLE IF NOT EXISTS tcg_sets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL UNIQUE,
    abbreviation VARCHAR(10) NOT NULL,
    era VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert abbreviations with Eras
INSERT INTO tcg_sets (name, abbreviation, era) VALUES
-- Scarlet & Violet Era
('Perfect Order', 'POR', 'Scarlet & Violet Era'),
('Ascended Heroes', 'ASC', 'Scarlet & Violet Era'),
('Mega Evolution', 'MEG', 'Scarlet & Violet Era'),
('Mega Evolution Promos', 'MEP', 'Scarlet & Violet Era'),
('Scarlet & Violet', 'SVI', 'Scarlet & Violet Era'),
('Paldea Evolved', 'PAL', 'Scarlet & Violet Era'),
('Obsidian Flames', 'OBF', 'Scarlet & Violet Era'),
('151', 'MEW', 'Scarlet & Violet Era'),
('Paradox Rift', 'PAR', 'Scarlet & Violet Era'),
('Paldean Fates', 'PAF', 'Scarlet & Violet Era'),
('Temporal Forces', 'TEF', 'Scarlet & Violet Era'),
('Twilight Masquerade', 'TWM', 'Scarlet & Violet Era'),
('Shrouded Fable', 'SFA', 'Scarlet & Violet Era'),
('Stellar Crown', 'SCR', 'Scarlet & Violet Era'),
('Prismatic Evolutions', 'PRE', 'Scarlet & Violet Era'),
('Surging Sparks', 'SSP', 'Scarlet & Violet Era'),
('Scarlet & Violet Black Star Promos', 'PR-SV', 'Scarlet & Violet Era'),
('Scarlet & Violet Energies', 'SVE', 'Scarlet & Violet Era'),
-- Sword & Shield Era
('Brilliant Stars', 'BRS', 'Sword & Shield Era'),
('Astral Radiance', 'ASR', 'Sword & Shield Era'),
('Pokémon GO', 'PGO', 'Sword & Shield Era'),
('Lost Origin', 'LOR', 'Sword & Shield Era'),
('Silver Tempest', 'SIT', 'Sword & Shield Era'),
('Crown Zenith', 'CRZ', 'Sword & Shield Era'),
('Sword & Shield', 'SSH', 'Sword & Shield Era'),
('Rebel Clash', 'RCL', 'Sword & Shield Era'),
('Darkness Ablaze', 'DAA', 'Sword & Shield Era'),
('Champion''s Path', 'CPA', 'Sword & Shield Era'),
('Vivid Voltage', 'VIV', 'Sword & Shield Era'),
('Shining Fates', 'SHF', 'Sword & Shield Era'),
('Battle Styles', 'BST', 'Sword & Shield Era'),
('Chilling Reign', 'CRE', 'Sword & Shield Era'),
('Evolving Skies', 'EVS', 'Sword & Shield Era'),
('Celebrations', 'CEL', 'Sword & Shield Era'),
('Fusion Strike', 'FST', 'Sword & Shield Era'),
-- Sun & Moon Era
('Sun & Moon', 'SUM', 'Sun & Moon Era'),
('Guardians Rising', 'GRI', 'Sun & Moon Era'),
('Burning Shadows', 'BUS', 'Sun & Moon Era'),
('Shining Legends', 'SLG', 'Sun & Moon Era'),
('Crimson Invasion', 'CIN', 'Sun & Moon Era'),
('Ultra Prism', 'UPR', 'Sun & Moon Era'),
('Forbidden Light', 'FLI', 'Sun & Moon Era'),
('Celestial Storm', 'CES', 'Sun & Moon Era'),
('Dragon Majesty', 'DRM', 'Sun & Moon Era'),
('Lost Thunder', 'LOT', 'Sun & Moon Era'),
('Team Up', 'TEU', 'Sun & Moon Era'),
('Detective Pikachu', 'DET', 'Sun & Moon Era'),
('Unbroken Bonds', 'UNB', 'Sun & Moon Era'),
('Unified Minds', 'UNM', 'Sun & Moon Era'),
('Hidden Fates', 'HIF', 'Sun & Moon Era'),
('Cosmic Eclipse', 'CEC', 'Sun & Moon Era'),
-- XY Era
('Kalos Starter Set', 'KSS', 'XY Era'),
('XY', 'XY', 'XY Era'),
('Flashfire', 'FLF', 'XY Era'),
('Furious Fists', 'FFI', 'XY Era'),
('Phantom Forces', 'PHF', 'XY Era'),
('Primal Clash', 'PRC', 'XY Era'),
('Double Crisis', 'DCR', 'XY Era'),
('Roaring Skies', 'ROS', 'XY Era'),
('Ancient Origins', 'AOR', 'XY Era'),
('BREAKthrough', 'BKT', 'XY Era'),
('BREAKpoint', 'BKP', 'XY Era'),
('Generations', 'GEN', 'XY Era'),
('Fates Collide', 'FCO', 'XY Era'),
('Steam Siege', 'STS', 'XY Era'),
('Evolutions', 'EVO', 'XY Era'),
-- Black & White Era
('Black & White', 'BLW', 'Black & White Era'),
('Emerging Powers', 'EPO', 'Black & White Era'),
('Noble Victories', 'NVI', 'Black & White Era'),
('Next Destinies', 'NXD', 'Black & White Era'),
('Dark Explorers', 'DEX', 'Black & White Era'),
('Dragons Exalted', 'DRX', 'Black & White Era'),
('Dragon Vault', 'DRV', 'Black & White Era'),
('Boundaries Crossed', 'BCR', 'Black & White Era'),
('Plasma Storm', 'PLS', 'Black & White Era'),
('Plasma Freeze', 'PLF', 'Black & White Era'),
('Plasma Blast', 'PLB', 'Black & White Era'),
('Legendary Treasures', 'LTR', 'Black & White Era'),
-- Diamond & Pearl Era
('Diamond & Pearl', 'DP', 'Diamond & Pearl Era'),
('Mysterious Treasures', 'MT', 'Diamond & Pearl Era'),
('Secret Wonders', 'SW', 'Diamond & Pearl Era'),
('Great Encounters', 'GE', 'Diamond & Pearl Era'),
('Majestic Dawn', 'MD', 'Diamond & Pearl Era'),
('Legends Awakened', 'LA', 'Diamond & Pearl Era'),
('Stormfront', 'SF', 'Diamond & Pearl Era'),
('Platinum', 'PL', 'Diamond & Pearl Era'),
('Rising Rivals', 'RR', 'Diamond & Pearl Era'),
('Supreme Victors', 'SV', 'Diamond & Pearl Era'),
('Arceus', 'AR', 'Diamond & Pearl Era'),
('HeartGold & SoulSilver', 'HS', 'Diamond & Pearl Era'),
('Unleashed', 'UL', 'Diamond & Pearl Era'),
('Undaunted', 'UD', 'Diamond & Pearl Era'),
('Triumphant', 'TM', 'Diamond & Pearl Era'),
('Call of Legends', 'CL', 'Diamond & Pearl Era'),
-- EX Era
('EX Ruby & Sapphire', 'RS', 'EX Era'),
('EX Sandstorm', 'SS', 'EX Era'),
('EX Dragon', 'DR', 'EX Era'),
('EX Team Magma vs Team Aqua', 'MA', 'EX Era'),
('EX Hidden Legends', 'HL', 'EX Era'),
('EX FireRed & LeafGreen', 'RG', 'EX Era'),
('EX Team Rocket Returns', 'TRR', 'EX Era'),
('EX Deoxys', 'DX', 'EX Era'),
('EX Emerald', 'EM', 'EX Era'),
('EX Unseen Forces', 'UF', 'EX Era'),
('EX Delta Species', 'DS', 'EX Era'),
('EX Legend Maker', 'LM', 'EX Era'),
('EX Holon Phantoms', 'HP', 'EX Era'),
('EX Crystal Guardians', 'CG', 'EX Era'),
('EX Dragon Frontiers', 'DF', 'EX Era'),
('EX Power Keepers', 'PK', 'EX Era'),
-- Neo Era
('Southern Islands', 'SI', 'Neo Era'),
('Neo Genesis', 'N1', 'Neo Era'),
('Neo Discovery', 'N2', 'Neo Era'),
('Neo Revelation', 'N3', 'Neo Era'),
('Neo Destiny', 'N4', 'Neo Era'),
('Legendary Collection', 'LC', 'Neo Era'),
('Expedition Base Set', 'EX', 'Neo Era'),
('Aquapolis', 'AQ', 'Neo Era'),
('Skyridge', 'SK', 'Neo Era'),
-- Base Set Era
('Base Set', 'BS', 'Base Set Era'),
('Jungle', 'JU', 'Base Set Era'),
('Fossil', 'FO', 'Base Set Era'),
('Base Set 2', 'B2', 'Base Set Era'),
('Team Rocket', 'TR', 'Base Set Era'),
('Gym Heroes', 'G1', 'Base Set Era'),
('Gym Challenge', 'G2', 'Base Set Era'),
-- McDonald's Collections
('2011 McDonald''s Collection', 'MCD', 'McDonald''s Collections'),
('2012 McDonald''s Collection', 'MCD', 'McDonald''s Collections'),
('2013 McDonald''s Collection', 'MCD', 'McDonald''s Collections'),
('2014 McDonald''s Collection', 'MCD', 'McDonald''s Collections'),
('2015 McDonald''s Collection', 'MCD', 'McDonald''s Collections'),
('2016 McDonald''s Collection', 'MCD', 'McDonald''s Collections'),
('2017 McDonald''s Collection', 'MCD', 'McDonald''s Collections'),
('2018 McDonald''s Collection', 'MCD', 'McDonald''s Collections'),
('2019 McDonald''s Collection', 'MCD', 'McDonald''s Collections'),
('2021 McDonald''s Collection', 'MCD', 'McDonald''s Collections'),
('2022 McDonald''s Collection', 'MCD', 'McDonald''s Collections')
ON CONFLICT (name) DO UPDATE SET era = EXCLUDED.era;
